version: "3.8"

services:
  app:
    image: natterstefan/nodejs-playground:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
